# Generated by Django 3.2.2 on 2021-09-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('freeship', 'freeship'), ('direct deduction', 'direct deduction'), ('percentage deduction', 'percentage deduction')], default='direct deduction', max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
                ('discount', models.DecimalField(decimal_places=1, max_digits=8)),
            ],
        ),
    ]
