# Generated by Django 3.2.2 on 2021-10-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coupon',
            table='coupon_coupon_update',
        ),
    ]
