# Generated by Django 3.2.2 on 2021-10-01 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_alter_coupon_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
