# Generated by Django 3.2.2 on 2021-10-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.CharField(choices=[('freeship', 'freeship'), ('direct deduction', 'direct deduction'), ('percentage deduction', 'percentage deduction'), ('promotion payment method', 'promotion payment method')], default='direct deduction', max_length=50),
        ),
    ]
