import { useEffect } from 'react'
import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
// import Link from 'next/link'
import { useSelector, useDispatch } from 'react-redux'
// import Button  from '../components/button/Button'
// import Checkbox from '../components/form/checkbox/Checkbox'
import PolicyCard from '../components/policycard/PolicyCard'
import InfinityList from '../components/infinitylist/InfinityList'


import Slider from '../components/slide/Slider'
import productApi from '../callApi/productApi'
import CardImage from '../components/cardimage/CardImage'
import List from '../components/list/List'
import { productPage } from '../utils/urls'
import {useRouter} from 'next/router'

const SliderData = [
  {
      title: "Polo nữ Pima cao cấp",
      description: "Nhắc đến sự đẳng cấp là không thể không nhắc đến dòng vải pima. Nó tạo nên chất lượng tốt nhất cho bất kỳ sản phẩm thời trang nào. Sợi vải pima dài và dày hơn sợi cotton thông thường gấp đôi nhờ công nghệ dệt tân tiến. Điều đó làm cho kết cấu áo polo chắc chắn, bền chặt, hạn chế tối đa xù lông, mềm mượt, bền màu, vô cùng đảm bảo sức khoẻ người dùng",
      img: '/slider1.png',
      color: "blue",
      path: "/"
  },
  {
      title: "Polo Nữ Dáng Suông Modal",
      description: "Polo nữ dáng suông Modal sử dụng công nghệ vải cao cấp thân thiện với môi trường sản xuất độc quyền chống co rút vải, áo polo nữ vải modal là sản phẩm thích hợp cho các bạn có môi trường làm việc năng động như hiện nay",
      img: '/slider2.png',
      path: "/",
      color: "pink"
  },
  {
      title: "Polo Nữ Coolmax Lacoste",
      description: "Mẫu áo polo nữ được làm bằng chất liệu coolmax đem lại cảm giác mát lạnh khi mặc. Thiết kế mẫu áo polo coolmax này có kiểu dáng cực kỳ thoải mái. Tạo sự gọn gàng hứa hẹn sẽ là mẫu áo polo vô cùng hot trong thời điểm sắp tới",
      img: '/slider3.png',
      path: "/",
      color: "orange"
  }
]

const policy = [
  {
      name: "Miễn phí giao hàng",
      description: "Miễn phí ship với đơn hàng > 239K",
      icon: "bx bx-shopping-bag"
  },
  {
      name: "Thanh toán COD",
      description: "Thanh toán khi nhận hàng (COD)",
      icon: "bx bx-credit-card"
  },
  {
      name: "Khách hàng VIP",
      description: "Ưu đãi dành cho khách hàng VIP",
      icon: "bx bx-diamond"
  },
  {
      name: "Hỗ trợ bảo hành",
      description: "Đổi, sửa đồ tại tất cả store",
      icon: "bx bx-donate-heart"
  }
]

const renderCategory = (item, index) => (
  <CardImage 
    key={index}
    name={item.name}
    description={item.description}
    image={item.background_image}
  />
)
export default function Home(props) {
  const router = useRouter()

  const renderCategory = (item, index) => (
    <div
      className='full_height'
      onClick={() => router.push({
        pathname: productPage(),
        query: {category: item.name}
      })}
      key={index}
    >
      <CardImage
        name={item.name}
        description={item.description}
        image={item.background_image}
      />
    </div>
  )
  
  
  return (
    <div>
      <Head>
        <title>Hello world</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="section" style={{height: "90vh"}}>
        <Slider 
              data={SliderData}
              control = {true}
              auto={true}
              timeOut={10000}
          />
      </div>

      <div className="max_width_1280 margin_center">
        <div className="section">
          <div className="grid grid-col-4 grid-col-md-2 grid-col-sm-1">
            {
              policy.map((item, index) => (
                <PolicyCard 
                  key={index}
                  name={item.name} 
                  icon={item.icon} 
                  description={item.description}/>
              ))
            }
          </div>  
        </div>
        <div className="section">
          <h4 className="section_title">Categories</h4>
          <List
            renderItem={(item, index) => renderCategory(item, index)}
            attr1='categories'
            attr2='data'
            dispatchFunction={() => {}}
            wraper_class='grid grid-col-6  grid-col-md-4 grid-col-sm-3'

        />
        </div>
        <div className="section">
          <h4 className="section_title">New Products</h4>
            <InfinityList 
              gap_col="30px"
              gap_row="40px"
            />
        </div>
      </div>
     
    
    </div>
  )
}
Home.defaultProps = {
  products: []
}

export async function getStaticProps() {
  try {
    const res = await productApi.getAll()
    console.log("res index ", res)
    const products = await res.json()
    console.log("json index page", products)
    return {
      props:{ 
        products: products
      },
      revalidate: 10
    }
  } catch (error) {
    return {
      props:{ 
        products: []
      },
      revalidate: 10
    }   
  }
}

