# Generated by Django 3.2.2 on 2021-08-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('unconfirmed', 'Unconfirmed'), ('confirmed', 'Comfirmed'), ('returned', 'Returned'), ('shipping', 'Shipping'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='draft', max_length=50),
        ),
    ]
