# Generated by Django 3.2.2 on 2021-10-03 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_method',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='ShippingMethod',
        ),
    ]
