# Generated by Django 3.2.2 on 2021-10-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20211003_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
