# Generated by Django 3.2.2 on 2021-06-04 01:01

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantcriterion',
            name='order',
            field=core.fields.OrderField(blank=True, null=True),
        ),
    ]
