# Generated by Django 3.2.2 on 2021-06-04 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productvariantcriterion_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariantcriterion',
            old_name='name',
            new_name='criterion_name',
        ),
        migrations.RenameField(
            model_name='productvariantoption',
            old_name='name',
            new_name='option_name',
        ),
    ]
