# Generated by Django 3.2.2 on 2021-06-04 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210604_0344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productvariantcriterion',
            name='order',
        ),
    ]
