# Generated by Django 3.2.2 on 2021-06-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_combind_sring_productvariant_combind_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(max_length=30),
        ),
    ]
