# Generated by Django 3.2.2 on 2021-07-13 10:23

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productvariant_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantcriterion',
            name='order',
            field=core.fields.OrderField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariantoption',
            name='order',
            field=core.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariantoption',
            name='criterion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='product.productvariantcriterion'),
            preserve_default=False,
        ),
    ]
