# Generated by Django 3.2.2 on 2021-08-01 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210714_0215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='backgroundImage',
            new_name='background_image',
        ),
    ]
