# Generated by Django 3.2.2 on 2021-08-07 04:15

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210807_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='order',
            field=core.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
