# Generated by Django 3.2.2 on 2021-08-09 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_productvariantoption_image_indexs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ('order',)},
        ),
    ]
