# Generated by Django 3.2.2 on 2021-08-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_productvariant_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='publication_date',
        ),
    ]
