# Generated by Django 3.2.2 on 2021-08-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_product_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
